name: flutter_weigh_serial
description: Provides electronic scale data acquisition capability, supporting Android and Windows platforms.
version: 1.0.0+2
author: lixiaohong<liyufengisme@gmail.com>
homepage: https://github.com/liyufengrex/flutter_weigh_serial

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  usb_serial: ^0.5.2
  serial_port_win32: ^1.3.0
  rxdart: ^0.27.7
  dartx: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

platforms:
  android:
  windows:

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.rex.flutter_weigh_serial
    iosBundleIdentifier: com.rex.flutterWeighSerial
